### ISSUE TITLE
How can I train the models provided in the paper

### ISSUE THREAD

**Issue by liyang268** [AdelaideAuto-IDLab/Februus#2]
I have trained some models, but I can't restore the effect of the paper. Can  provide some training model code.

**Comment by baogiadoan** [comment]
hi @liyang268 , the poisoning process is quite straightforward and well implemented in the literature, that's why, for convenience, we only provided the pre-trained models with the corresponding trigger artifacts and network architectures, I'll add this add a TODO to allocate the resources to look back the training code.
